WebServerEmployee/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using WebServerEmployee.BL.Implementations;
using WebServerEmployee.BL.Interfaces;

namespace WebServerEmployee.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyBL _companyBL;
        public CompanyController(ICompanyBL companyBL)
        {
            _companyBL = companyBL;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllCompanies()
        {
            var response = await _companyBL.GetAllCompanies();
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return RedirectToAction("MyError", "MyError", response);// переход на представление, которое будет отображать ошибку

        }
        
    }
}

WebServerEmployee/Controllers/EmployeeController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using WebServerEmployee.BL.Implementations;
using WebServerEmployee.BL.Interfaces;
using WebServerEmployee.DAL.Interfaces;
using WebServerEmployee.Domain.Entity;
using WebServerEmployee.Domain.Response;
using WebServerEmployee.Domain.ViewModel;

namespace WebServerEmployee.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeBL _employeeBL;
        public EmployeeController(IEmployeeBL employeeBL)
        {
            _employeeBL = employeeBL;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllEmployees()
        {
            var response = await _employeeBL.GetAllEmployees();
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return RedirectToAction("MyError", "MyError", response); // переход на представление, которое будет отображать ошибку

        }

        [HttpGet]
        public async Task<IActionResult> GetEmployee(int id)
        {
            var response = await _employeeBL.GetEmployee(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return RedirectToAction("MyError", "MyError", response);// переход на представление, которое будет отображать ошибку

        }

        [HttpGet]
        public async Task<IActionResult> DeleteEmployee(int id)
        {
            if (id == 0)
            {
                return View();
            }
            var response = await _employeeBL.DeleteEmployee(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("GetAllEmployees"); // преход на представление, отображающее всех сотрудников
            }
            return RedirectToAction("MyError", "MyError", response); // переход на представление, которое будет отображать ошибку
        }

        [HttpPost]
        public async Task<IActionResult> DeleteEmployee(Employee employee)
        {
            if(employee.EmployeeID != 0)
            {
                var response = await _employeeBL.DeleteEmployee((employee.EmployeeID));
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return RedirectToAction("GetAllEmployees"); // преход на представление, отображающее всех сотрудников
                }
            }
           
            return RedirectToAction("MyError", "MyError", new BaseResponse<Employee> { Description = "Сотрудник с таким Id не найден", StatusCode = Domain.Enum.StatusCode.ObjNotFound });
        }


        // добавление/изменение пользователей
        [HttpGet]
        public async Task<IActionResult> Save(int id)
        {

            // если == 0, то это добавление нового объекта в бд
            if (id == 0)
            {
                return View();
            }
            // иначе изменение имеющегося объекта
            var response = await _employeeBL.GetEmployee(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data); // преход на представление, отображающее всех сотрудников
            }
            return RedirectToAction("MyError", "MyError", response); // переход на представление, которое будет отображать ошибку
        }

        [HttpPost]
        public async Task<IActionResult> Save(EmployeeViewModel employeeViewModel)
        {
            if (employeeViewModel.EmployeeID == 0)
            {
                 var response = await _employeeBL.CreateEmployee(employeeViewModel); // создаем нового сотрудника

                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return RedirectToAction("GetEmployee", new { id = response.Data.EmployeeID });
                }
                return RedirectToAction("MyError", "MyError", response);

            }
            else
            {
                var response = await _employeeBL.EditEmployee(employeeViewModel); // изменяем сотрудника
                
                if (response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    return RedirectToAction("GetEmployee", new { id = employeeViewModel.EmployeeID });
                }
                return RedirectToAction("MyError", "MyError", response);
            }
        }

        [HttpGet]
        public async Task<IActionResult> UpdateEmployeeById(int id)
        {
            if (id == 0)
            {
                return View();
            }
            // иначе изменение имеющегося объекта
            var response = await _employeeBL.GetEmployee(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data); // преход на представление, отображающее всех сотрудников
            }
            return RedirectToAction("MyError", "MyError", response); // переход на представление, которое будет отображать ошибку
        }
        //void
        [HttpPost]
        public async Task<IActionResult> UpdateEmployeeById(Employee employee)
        {
            return  RedirectToAction("Save", new { id = employee.EmployeeID });
        }

        [HttpGet]
        public async Task<IActionResult> GetEmployeeByCompany(int id, Employee employee)
        {
            var response = await _employeeBL.GetEmployeeByCompany(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data); // преход на представление, отображающее всех сотрудников
            }
            return RedirectToAction("MyError", "MyError",  response ); // переход на представление, которое будет отображать ошибку
        }

        [HttpGet]
        public async Task<IActionResult> GetEmployeeByDepartment(int id)
        {
            var response = await _employeeBL.GetEmployeeByDepartment(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);// преход на представление, отображающее всех сотрудников
            }
            return RedirectToAction("MyError", "MyError", response); // переход на представление, которое будет отображать ошибку
        }
    }
}

WebServerEmployee/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebServerEmployee.DAL.Interfaces;
using WebServerEmployee.Domain.Entity;
using WebServerEmployee.Models;

namespace WebServerEmployee.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebServerEmployee/Views/Home/Create.cshtml
@model WebServerEmployee.Domain.Entity.Employee

@{
    ViewData["Title"] = "Новый пользователь";
}
<h2>@ViewData["Title"]</h2>

<form asp-action="Create" asp-controller="Home">
    <div>
        <div class="form-group">
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" class="form-control form-control-sm" />
        </div>
        <div class="form-group">
            <label asp-for="Surname"></label>
            <input asp-for="Surname" class="form-control  form-control-sm" />
        </div>

        <div class="form-group">
            <label asp-for="Phone_number"></label>
            <input asp-for="Phone_number" class="form-control  form-control-sm" />
        </div>

        <div class="form-group">
            <label asp-for="CompanyID"></label>
            <input asp-for="CompanyID" class="form-control  form-control-sm" />
        </div>

        <div class="form-group">
            <label asp-for="PassportID"></label>
            <input asp-for="PassportID" class="form-control  form-control-sm" />
        </div>

        <div class="form-group">
            <label asp-for="DepartmentID"></label>
            <input asp-for="DepartmentID" class="form-control  form-control-sm" />
        </div>

        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
        </div>
    </div>
</form>

<div>
    <a asp-controller="Home" asp-action="Index">Вернуться к списку</a>
</div>

WebServerEmployee/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "WebServerEmployee";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a class="flex-sm-fill text-sm-center nav-link" asp-controller="Employee" asp-action="GetAllEmployees"> Показать всех сотрудников </a>
    <a class="flex-sm-fill text-sm-center nav-link" asp-controller="Employee" asp-action="Save"> Добавить нового сотрудника </a>
    <a class="flex-sm-fill text-sm-center nav-link" asp-controller="Employee" asp-action="DeleteEmployee"> Удалить сотрудника по Id </a>
    <a class="flex-sm-fill text-sm-center nav-link" asp-controller="Employee" asp-action="UpdateEmployeeById"> Изменить сотрудника по Id </a>
    <a class="flex-sm-fill text-sm-center nav-link" asp-controller="Company" asp-action="GetAllCompanies"> Показать все компании </a>
</div>

WebServerEmployee/Views/Home/Print.cshtml
@*@using WebServerEmployee.Domain.Entity.Employee
@model Employee*@
@model int
@{
    ViewData["Title"] = "Print";
}
<div class="card col-md-12">
    <p class="text-center">@Model</p>
</div>